### ISSUE TITLE
Automate localized file generation process

### ISSUE THREAD

**Issue by SlnPons** [massalabs/massa-localized-docs#2] opened 2022-11-08 15:27 UTC
**Context** 
Automate the current process of `.po` file generation to simplify as much as possible the process of translating the doc into another language. 
We're not looking for an industrialised translation of our documentation. The documentation is still not ready in one language yet. The idea here is simply to start the automation of this proccess. 

**Needs** 
* As a user, I want to be able to generate the creation of the all the file needed to translate the Massa doc into a specific language really easily. 
* As Massa, I want to be able to identify if the latest version of the documentation is translated or not and in which language easily by looking at the version number of each documentation (original vs translated one)

**How to**
- [ ] To generate the file .po for a specific language based on the orginal file contain on this repo: https://github.com/massalabs/massa-docs
- [ ] To version the original english doc so that when it's updated the localized doc reflects the update and missing parts
Document and discuss best we should manage this 2nd point. 

**Technical details**
To be added by the dev

**Comment by thomas-senechal** [comment] 2022-11-15 15:17
First of all, I think we should discuss about how we want to handle the localization since this will necessarily change the translation process.

## Repository management

We can handle the localizations of the documentation in 3 ways:

### Option 1
We can use the same repository for the documentation and all the languages, and use the `locale` folder to store the different languages as it has been tested in [Massa Docs c695834](https://github.com/massalabs/massa-docs/tree/c695834cfa0b8d3906b9e9f943aef82c8c4af4fb).

#### Pros and cons
Pros: 
- Only one repository to manage.
- No submodules to manage.

Cons:
- The repository will get bigger and bigger as people add more languages and might get hard to manage.
- Might get difficult to manage all the PRs and issues in a single repository.


### Option 2
We can use 2 repositories, one for the documentation (`massa-docs`) and one for the localizations (`massa-localized-docs`). The documentation repository will contain the `locale` folder which will be a link of the localizations repository, and the localizations repository will contain the different languages translations.

#### Technical details
It is possible to tell ReadTheDocs to pull submodules using the [`submodules` configuration](https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules) in a `.readthedocs.yaml` file. This would allow us to use the `massa-localized-docs` repository as a submodule of the `massa-docs` repository.

In `massa-localized-docs`, we could have `massa-docs` as a submodule or clone it during the translation process.

#### Pros and cons
Pros: 
- The documentation repository will be cleaner and easier to maintain.
- The documentation repository will be only used by the team and the localizations repository will be mainly used by the community.
- This could allow us to rely more on the community to review the PRs without having to worry about bad translations in the `massa-docs` repository.

Cons:
- Might be more complicated to maintain if we don't implement the connection between the 2 repositories correctly.
- If using submodule, we will have to update the submodule language when we update the documentation (we could use Github Actions to do it automatically).


### Option 3
We could have a repository for each language. The documentation repository will contain the `locale` which will contains a references or clones of the different languages repositories. The different languages repositories will contain the documentation in their respective language in `.po` files.

#### Technical details
Highly similar to option 2, but with a submodules for each language instead of one for all the languages. 

#### Pros and cons
Pros: 
- ...

Cons:
- Will get harder to maintain as the number of languages increases.
- If using submodules, we will have to update the submodules for each language when we update the documentation (we could use Github Actions to do it automatically).

## Personal opinion

I think that option 2 is the best option. It is the most flexible and the most maintainable. It is not the easiest to implement, but it is not that complicated either. And I think that it is also the option that will require the least work from the team once it is implemented.


@SlnPons @qdrn What do you think about that ?

**Comment by qdrn** [comment] 2022-11-15 17:20
Option 2 sounds good. That's also what I saw on other projects. Can you implement it ? If you need access or anything feel free to ping me.

**Comment by SlnPons** [comment] 2022-11-16 15:33
Option 2 looks good to me too. Cheers.

**Comment by thomas-senechal** [comment] 2022-11-16 15:36
Now that we know how we will handle our repositories, I'd like your opinion on how we manage the translation files and so, the user journey. 

## Context

As proposed by [ReadTheDocs documentation](https://docs.readthedocs.io/en/stable/guides/manage-translations-sphinx.html#manage-translations-for-sphinx-projects), we can use `sphinx`, and especially `sphinx-intl` to manage translations.

First, we need to generate the `.pot` files which will contain the strings to translate. This is done using `sphinx-build -b gettext . _build/gettext` in the `docs` folder. The `.pot` files will be generated in the `_build/gettext` folder.

Then, we need to generate the `.po` files for each language using `sphinx-intl` as follow: `sphinx-intl update -p _build/gettext -l <language>`. The `.po` files will be generated in the `locale/<language>/LC_MESSAGES` folder. 

Finally, it is possible to use `sphinx-build -b html -D language=<language> . _build/html` in the `docs` folder to generate the documentation in the requested language. The generated documentation will be in the `_build/html` folder. It is possible to start a local server to view the documentation using `python -m http.server` in the `_build/html` folder.

> Note: `_build/gettext` is the folder suggested by ReadTheDocs but we can definitely use something else.

### Proposed user journey

1. A user wants to contribute to the documentation and wants to translate it in a new language.
2. The user creates a fork of the `massa-localized-docs` repository.
3. The user follows the steps to install the dependencies.
4. The user uses a given script/command to generate/update the `.po` files.
5. The user translates the strings in the `.po` files.
6. The user creates a pull request to the main repository.

### Technical details

Firstly, we will need people to install `sphinx`. This could be done using a script, but since all the tools required to work on the translations are available through `pip`, we could just add a `requirements.txt` file to the documentation repository and ask users to install the requirements using `pip install -r requirements.txt`. 

Secondly, we might need a script to perform some actions like generate/update the `.po` files.

#### Read the docs recommendations

ReadTheDocs recommands to set [`gettext_uuid`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_uuid) to `True` in the `conf.py` file. This would allow `sphinx` to generate uuid information in the `.pot` file to keep track of the translations even if the text changes. The issue is that we would need to keep the `.pot` file in the repository to keep track of the translations. This would mean that we would need to update the `.pot` file each time we update the documentation. This could be done automatically using Github Actions.

ReadTheDocs also recommends to set the [`gettext_compact`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_compact) option to `False` in the `conf.py` file. This option concatenates all the pages of a section into a single `.po` file instead of having one `.po` file per page. For example, the [`technical-doc`](https://github.com/massalabs/massa-docs/tree/c695834cfa0b8d3906b9e9f943aef82c8c4af4fb/technical-doc) folder will be translated into a single [`technical-doc.po`](https://github.com/massalabs/massa-docs/blob/c695834cfa0b8d3906b9e9f943aef82c8c4af4fb/locales/fr/LC_MESSAGES/technical-doc.po) file instead of having one `.po` file per page. Even if it makes less files, it makes files bigger and harder to manage. I also think that it can be confusing and discouraging for the translators to have to translate a single file with 1000 lines instead of 10 files with 100 lines.


## Translation process proposal
> Note: Those are proposals and are open to discussion.

### Option 1

Store the `.pot` files in the repository and update them regularly.

In that case, we might not need the second script since it will be reduced to a simple `sphinx-intl update -p _build/gettext -l <language>`.

#### Pros and cons
Pros:
- Easy to use for translators.
- Easy to maintain once it is set up.

Cons:
- Needs a Github Workflow to update the `.pot` files.

### Option 2

Not store the `.pot` files in the repository and let the users generate them.

In that case, the second script will do the following steps:
- Clone `massa-docs` or update a submodule linked to `massa-docs`.
- Generate the `.pot` file using `sphinx-build -b gettext . _build/gettext`.
- Run `sphinx-intl update -p _build/gettext -l <language>` to generate/update the `.po` files for the language `<language>`.

> 
> Notes: 
>     - The language `<language>` can be a parameter of the script or asked to the user during the execution of the script.
>     - Since `sphinx-build` is using `.` as source, we might need to copy the file of `massa-docs` at the root of the repository before running the command.

#### Pros and cons
Pros:
- No workflow required.

Cons:
- More points of failure on translators side, so possibly more issues to handle if it happens.
- Will have more files to review in each PR since people might push `.po` files that might have been updated by `sphinx-intl`.


## Personal opinion

In my opinion, we should use the Option 1 and so,  set `gettext_uuid` to `True` and `gettext_compact` to False as recommanded by ReadTheDocs. We can update the `.pot` files regularly using Github Workflows (let's say everytime something has been pushed on `massa-docs`). This would allow us to keep a track of our translations while making sure that people won't upload `.pot` files.

@qdrn @SlnPons Which option seems the best for you ? 
If you have any questions, feel free to ask them here or ping me somewhere else.

**Comment by qdrn** [comment] 2022-11-21 09:59
Option 1 looks better.

I don't expect user to add language. This can be asked through issue and we'll do it ourselves. We'll just start with a couple of languages.

**Closed as completed** 2022-12-12 12:15 UTC
